export const allProjects: any[] = [
  {
    _id: "string",
    _raw: {},
    type: "Project",
    published: false,
    winner: false,
    winnerTitle: "",
    title: "SovID",
    skills: ["a", "b", "c", "d"],
    description:
      "Sovid is a decentralised identity and credentials management protocol on LightLink chain. SovID is your gateway to sovereign identity. We are leveraging LightLink Infrastructure to mint digital identities and credentials as NFTs (in form of SBTs).",
    list1: "dgsterdfxhgcvnb cxcsderwr6y7tfugyhjnb svdfrtryhujynhgbvc",
    list2: "dgsterdfxhgcvnb cxcsderwr6y7tfugyhjnb svdfrtryhujynhgbvc",
    date: "2024-01-31T00:00:00.000Z",
    url: "sov-id.vercel.app/",
    repository: "0xAlphaDevs/SovID",
    body: { code: "" },
    path: "string",
    slug: "01",
  },
  {
    _id: "string",
    _raw: {},
    type: "Project",
    published: false,
    winner: true,
    winnerTitle: "LFGHO | ETH Gobal",
    title: "DeWork",
    skills: ["a", "b", "c", "d"],
    description:
      "A Decentralized freelancing platform connecting businesses and professionals | Built during LFGHO",
    list1: "Won family pool prize at LFGHO organized by ETH Global",
    list2: "",
    date: "2024-01-16T00:00:00.000Z",
    url: "dework-khaki.vercel.app/",
    repository: "0xAlphaDevs/DeWork",
    body: { code: "" },
    path: "string",
    slug: "02",
  },
  {
    _id: "string",
    _raw: {},
    type: "Project",
    winner: true,
    winnerTitle: "DIF Hackathon",
    published: false,
    title: "HealthX Protocol",
    skills: ["a", "b", "c", "d"],
    description:
      "Own & Carry your Health History with Web5 - Seamlessly store and share medical records on decentralized web nodes (DWNs) using decentralized identifiers (DIDs). ",
    list1: "dgsterdfxhgcvnb cxcsderwr6y7tfugyhjnb svdfrtryhujynhgbvc",
    list2: "dgsterdfxhgcvnb cxcsderwr6y7tfugyhjnb svdfrtryhujynhgbvc",
    date: "2023-12-19T00:00:00.000Z",
    url: "healthx-ivory.vercel.app/",
    repository: "0xAlphaDevs/HealthX-DIF-hackathon",
    body: { code: "" },
    path: "string",
    slug: "03",
  },
  {
    _id: "string",
    _raw: {},
    type: "Project",
    published: false,
    winner: true,
    winnerTitle: "Encode X Mintbase 2023 Hackathon",
    title: "AI NFTs",
    skills: ["a", "b", "c", "d"],
    description:
      "Won under the Mintbase SDK category in the Encode X Near Horizon powered NEARDevHub. AI NFTs is platform that allows artists and AI algorithms to collaborate in the creation of unique NFT artworks. You can create art from text and scribbles, enter prompt and click on Generate Art. Add NFT details such as name, description and click on Mint NFT. This uploads the image to Arweave and creates an NFT using Mintbase SDK.",
    list1: "dgsterdfxhgcvnb cxcsderwr6y7tfugyhjnb svdfrtryhujynhgbvc",
    list2: "dgsterdfxhgcvnb cxcsderwr6y7tfugyhjnb svdfrtryhujynhgbvc",
    date: "2023-10-06T00:00:00.000Z",
    url: "ai-nfts-sooty.vercel.app/",
    repository: "0xAlphaDevs/ai-nfts-mintbase",
    body: { code: "" },
    path: "string",
    slug: "04",
  },

  {
    _id: "string",
    _raw: {},
    type: "Project",
    published: false,
    winner: true,
    winnerTitle: "The Actual Open AI Hackathon",
    title: "Alpha Marketplace",
    skills: ["a", "b", "c", "d"],
    description:
      "Alpha Marketplace is an innovative platform developed by AlphaDevs during the OpenAI Hackathon.",
    list1: "dgsterdfxhgcvnb cxcsderwr6y7tfugyhjnb svdfrtryhujynhgbvc",
    list2: "dgsterdfxhgcvnb cxcsderwr6y7tfugyhjnb svdfrtryhujynhgbvc",
    date: "2023-09-15T00:00:00.000Z",
    url: "https://nrqve4t77nxkgbt5j7gchxx3qbbf3pso5x37vozdl3byxjb2qwfq.arweave.net/bGFScn_7bqMGfU_MI977gEJdvk7t9_q7I17Di6Q6hYs/",
    repository: "0xyshv/image-marketplace.git",
    body: { code: "" },
    path: "string",
    slug: "05",
  },
  // {
  //   _id: "string",
  //   _raw: {},
  //   type: "Project",
  //   published: false,
  //   winner: false,
  //   title: "Atlassian-Forge-Jira-Summarizer",
  //   skills: ["a", "b", "c", "d"],
  //   description:
  //     "An app that condenses Jira issue descriptions and auto-generates PR summaries for streamlined project management.A trained model (llama-2-7b-chat) is used to summarize text in Jira Software issues. This Jira app intelligently summarizes text within Jira issues, providing clear overviews of complex and lengthy technical descriptions. The app uses Jira APIs, forge cli and forge api libraries to achieve this.",
  //   list1: "dgsterdfxhgcvnb cxcsderwr6y7tfugyhjnb svdfrtryhujynhgbvc",
  //   list2: "dgsterdfxhgcvnb cxcsderwr6y7tfugyhjnb svdfrtryhujynhgbvc",
  //   date: "2023-10-25T00:00:00.000Z",
  //   url: "https://developer.atlassian.com/console/install/739e4d67-7f9e-409e-ad84-73ac9fbebc91?signature=5f2864f58d8c12b7754e0b767bd5c40c5425f55f0b8b72ac767d2928eb73c262a8004b312199ee15deb853265a1c0d34c405619e93cd171d9b5278c341c5a066&product=jira",
  //   repository: "0xAlphaDevs/Atlassian-Forge-Jira-Summarizer",
  //   body: { code: "" },
  //   path: "string",
  //   slug: "06",
  // },
];

export const carouselImages: Record<string, string[]> = {
  "01": [
    "/sovid/ad1.jpeg",
    "/sovid/ad2.jpeg",
    "/sovid/ad3.jpeg",
    "/sovid/ad4.jpeg",
    "/sovid/ad5.jpeg",
    "/sovid/ad6.jpeg",
    "/sovid/ad7.jpeg",
  ],
  "02": [
    "/dework/1.png",
    "/dework/2.png",
    "/dework/3.png",
    "/dework/4.png",
    "/dework/5.png",
    "/dework/6.png",
  ],
  "03": [
    "/healthX/1.png",
    "/healthX/2.png",
    "/healthX/3.png",
    "/healthX/4.png",
    "/healthX/5.png",
    "/healthX/6.png",
  ],
  "04": [
    "/ainfts/1.png",
    "/ainfts/2.png",
    "/ainfts/3.png",
    "/ainfts/4.png",
    "/ainfts/5.png",
    "/ainfts/6.png",
    "/ainfts/7.png",
    "/ainfts/8.png",
    "/ainfts/9.png",
    "/ainfts/10.png",
  ],
  "05": [
    "/alpha-marketplace/1.png",
    "/alpha-marketplace/2.png",
    "/alpha-marketplace/3.png",
    "/alpha-marketplace/4.png",
  ],
  // "06": ["favicon.png", "favicon.png"],
};
