export const allProjects: any[] = [
  {
    _id: "string",
    _raw: {},
    type: "Project",
    published: false,
    winner: false,
    winnerTitle: "",
    title: "SovID",
    skills: ["EVM", "ERC 721", "Wagmi", "Material Tailwind"],
    description:
      "Sovid is a decentralised identity and credentials management protocol on LightLink chain. SovID is your gateway to sovereign identity. We are leveraging LightLink Infrastructure to mint digital identities and credentials as NFTs (in form of SBTs).",
    list1: "dgsterdfxhgcvnb cxcsderwr6y7tfugyhjnb svdfrtryhujynhgbvc",
    list2: "dgsterdfxhgcvnb cxcsderwr6y7tfugyhjnb svdfrtryhujynhgbvc",
    date: "2024-01-31T00:00:00.000Z",
    url: "sov-id.vercel.app/",
    repository: "0xAlphaDevs/SovID",
    body: { code: "" },
    path: "string",
    slug: "01",
  },
  {
    _id: "string",
    _raw: {},
    type: "Project",
    published: false,
    winner: true,
    winnerTitle: "LFGHO | ETH Gobal",
    title: "DeWork",
    skills: ["DeFi | Stablecoin", "Radix UI", "Next.js 14", "Wagmi"],
    description:
      "A Decentralized freelancing platform connecting businesses and professionals | Built during LFGHO",
    list1: "Won family pool prize at LFGHO organized by ETH Global",
    list2: "",
    date: "2024-01-16T00:00:00.000Z",
    url: "dework-khaki.vercel.app/",
    repository: "0xAlphaDevs/DeWork",
    body: { code: "" },
    path: "string",
    slug: "02",
  },

  {
    _id: "string",
    _raw: {},
    type: "Project",
    winner: false,
    winnerTitle: "Web5 Hackathon",
    published: false,
    title: "CredX",
    skills: ["DIDs", "DWNs", "VCs", "Recoil"],
    description:
      "CredX is a platform where users can own their data with Web5, can seamlessly store and share records on decentralized web nodes (DWNs) using decentralized identifiers (DIDs). Allowing admins to issue secure verifiable credentials (VCs) to users using their DIDs and providing the ownership of the data to the users.",
    list1: "",
    list2: "dgsterdfxhgcvnb cxcsderwr6y7tfugyhjnb svdfrtryhujynhgbvc",
    date: "2023-12-24T00:00:00.000Z",
    url: "healthx-ivory.vercel.app/",
    repository: "0xAlphaDevs/HealthX-DIF-hackathon",
    body: { code: "" },
    path: "string",
    slug: "03",
  },
  {
    _id: "string",
    _raw: {},
    type: "Project",
    winner: true,
    winnerTitle: "DIF Hackathon",
    published: false,
    title: "HealthX Protocol",
    skills: ["DIDs", "DWNs", "Radix UI"],
    description:
      "Own & Carry your Health History with Web5 - Seamlessly store and share medical records on decentralized web nodes (DWNs) using decentralized identifiers (DIDs). ",
    list1:
      "Won the third prize under the main DIF pool prize and sponsor's prize under TBD Block. ",
    list2: "dgsterdfxhgcvnb cxcsderwr6y7tfugyhjnb svdfrtryhujynhgbvc",
    date: "2023-11-19T00:00:00.000Z",
    url: "healthx-ivory.vercel.app/",
    repository: "0xAlphaDevs/HealthX-DIF-hackathon",
    body: { code: "" },
    path: "string",
    slug: "04",
  },
  {
    _id: "string",
    _raw: {},
    type: "Project",
    published: false,
    winner: true,
    winnerTitle: "Encode X Mintbase 2023 Hackathon",
    title: "AI NFTs",
    skills: [
      "Near Blockchain",
      "Mintbase SDK",
      "Replicate | ControlNet AI Modal",
    ],
    description:
      "AI NFTs is platform that allows artists and AI algorithms to collaborate in the creation of unique NFT artworks. You can create art from text and scribbles using Mintbase sdk. ",
    list1:
      "Won under the Mintbase SDK category in the Encode X Near Horizon 2023 Hackathon powered by NEARDevHub.",
    list2:
      "The app uses replicate & controlnet to generate images from text and scriibles, then uploads it to arweave and creates an NFT using Mintbase sdk. ",
    date: "2023-10-06T00:00:00.000Z",
    url: "ai-nfts-sooty.vercel.app/",
    repository: "0xAlphaDevs/ai-nfts-mintbase",
    body: { code: "" },
    path: "string",
    slug: "05",
  },

  {
    _id: "string",
    _raw: {},
    type: "Project",
    published: false,
    winner: true,
    winnerTitle: "The Actual Open AI Hackathon",
    title: "Alpha Marketplace",
    skills: ["Arweave", "GraphQL", "React"],
    description:
      "Alpha Marketplace is an innovative platform developed during the OpenAI Hackathon.",
    list1: "Won the prize for the best use case of UDL tags for license fees. ",
    list2: "dgsterdfxhgcvnb cxcsderwr6y7tfugyhjnb svdfrtryhujynhgbvc",
    date: "2023-09-15T00:00:00.000Z",
    url: "https://nrqve4t77nxkgbt5j7gchxx3qbbf3pso5x37vozdl3byxjb2qwfq.arweave.net/bGFScn_7bqMGfU_MI977gEJdvk7t9_q7I17Di6Q6hYs/",
    repository: "0xyshv/image-marketplace.git",
    body: { code: "" },
    path: "string",
    slug: "06",
  },
];

export const carouselImages: Record<string, string[]> = {
  "01": [
    "/sovid/ad1.jpeg",
    "/sovid/ad2.jpeg",
    "/sovid/ad3.jpeg",
    "/sovid/ad4.jpeg",
    "/sovid/ad5.jpeg",
    "/sovid/ad6.jpeg",
    "/sovid/ad7.jpeg",
  ],
  "02": [
    "/dework/1.png",
    "/dework/2.png",
    "/dework/3.png",
    "/dework/4.png",
    "/dework/5.png",
    "/dework/6.png",
  ],
  "03": [
    "/healthX/1.png",
    "/healthX/2.png",
    "/healthX/3.png",
    "/healthX/4.png",
    "/healthX/5.png",
    "/healthX/6.png",
  ],
  "04": [
    "/healthX/1.png",
    "/healthX/2.png",
    "/healthX/3.png",
    "/healthX/4.png",
    "/healthX/5.png",
    "/healthX/6.png",
  ],
  "05": [
    "/ainfts/1.png",
    "/ainfts/2.png",
    "/ainfts/3.png",
    "/ainfts/4.png",
    "/ainfts/5.png",
    "/ainfts/6.png",
    "/ainfts/7.png",
    "/ainfts/8.png",
    "/ainfts/9.png",
    "/ainfts/10.png",
  ],
  "06": [
    "/alpha-marketplace/1.png",
    "/alpha-marketplace/2.png",
    "/alpha-marketplace/3.png",
    "/alpha-marketplace/4.png",
  ],
  // "06": ["favicon.png", "favicon.png"],
};
