export const allProjects: any[] = [
  {
    _id: "string",
    _raw: {},
    type: "Project",
    published: false,
    title: "Buisness Consulting Hub",
    description:
      "The Buisness Consulting Hub frontend with Tailwind CSS Integration is a dynamic and responsive web application that leverages the capabilities of Next.js for seamless page routing and Tailwind CSS for rapid and consistent UI development. This project focuses on creating a smooth user experience, efficient development workflows, and a visually appealing design.",
    date: "2023-05-15T00:00:00.000Z",
    url: "https://nextjs-tailwind-ui-4.vercel.app/",
    repository: "0xyshv/nextjs-tailwind-ui-4.git",
    body: { code: "" },
    path: "string",
    slug: "06",
  },
  {
    _id: "string",
    _raw: {},
    type: "Project",
    published: false,
    title: "Drum Kit",
    description:
      "The Interactive JavaScript Drum Kit Project is an engaging web application that allows users to experience the joy of playing a virtual drum kit right in their browser. Built using HTML, CSS, and JavaScript, this project combines user interactivity with audio functionality to create an immersive drumming experience.",
    date: "2022-02-16T00:00:00.000Z",
    url: "https://0xyshv.github.io/drum-kit/",
    repository: "0xyshv/drum-kit",
    body: { code: "" },
    path: "string",
    slug: "08",
  },
  {
    _id: "string",
    _raw: {},
    type: "Project",
    published: false,
    title: "Stone Paper Scissor",
    description:
      "The Interactive Stone Paper Scissors Game is a fun and engaging web application built using JavaScript. This project brings the classic game of Rock-Paper-Scissors to the digital world, offering an interactive experience that allows users to play against a computer opponent.",
    date: "2021-12-30T00:00:00.000Z",
    url: "https://0xyshv.github.io/stone-paper-scissor/",
    repository: "0xyshv/stone-paper-scissor.git",
    body: { code: "" },
    path: "string",
    slug: "07",
  },
  {
    _id: "string",
    _raw: {},
    type: "Project",
    published: false,
    title: "Alpha Marketplace Front-end",
    description:
      "Alpha Marketplace is an innovative platform developed by AlphaDevs during the OpenAI Hackathon. Leveraging Arweave Blockchain and AI classifiers, it allows users to tag, upload, and license images. With React.js frontend and an Express backend, it seamlessly connects wallets and facilitates easy asset queries, ensuring creator recognition and monetization.",
    date: "2023-09-15T00:00:00.000Z",
    url: "https://nrqve4t77nxkgbt5j7gchxx3qbbf3pso5x37vozdl3byxjb2qwfq.arweave.net/bGFScn_7bqMGfU_MI977gEJdvk7t9_q7I17Di6Q6hYs/",
    repository: "0xyshv/image-marketplace.git",
    body: { code: "" },
    path: "string",
    slug: "01",
  },
  {
    _id: "string",
    _raw: {},
    type: "Project",
    published: false,
    title: "AI NFTs",
    description:
      "AI NFTs is platform that allows artists and AI algorithms to collaborate in the creation of unique NFT artworks. You can create art from text and scribbles, enter prompt and click on Generate Art. Add NFT details such as name, description and click on Mint NFT. This uploads the image to Arweave and creates an NFT using Mintbase SDK.",
    date: "2023-10-06T00:00:00.000Z",
    url: "ai-nfts-sooty.vercel.app/",
    repository: "https://github.com/0xAlphaDevs/ai-nfts-mintbase",
    body: { code: "" },
    path: "string",
    slug: "02",
  },
  {
    _id: "string",
    _raw: {},
    type: "Project",
    published: false,
    title: "P4W3-sbtify-user-dapp",
    description:
      "This is the user dashboard dApp for SBTify - a verifiable vredentials platform using Soul Bound Tokens (SBTs) on Oasis’s Sapphire Confidential EVM. Users can view all the SBTs issued by all the organizations. Under verifications requests tab, users can allow access or reject the verification request by a wallet/organization. ",
    date: "2023-10-15T00:00:00.000Z",
    url: "sbtify-user.vercel.app/",
    repository: "https://github.com/0xAlphaDevs/P4W3-sbtify-user-dapp",
    body: { code: "" },
    path: "string",
    slug: "03",
  },
  {
    _id: "string",
    _raw: {},
    type: "Project",
    published: false,
    title: "Atlassian-Forge-Jira-Summarizer",
    description:
      "An app that condenses Jira issue descriptions and auto-generates PR summaries for streamlined project management.A trained model (llama-2-7b-chat) is used to summarize text in Jira Software issues. This Jira app intelligently summarizes text within Jira issues, providing clear overviews of complex and lengthy technical descriptions. The app uses Jira APIs, forge cli and forge api libraries to achieve this.",
    date: "2023-10-25T00:00:00.000Z",
    url: "https://developer.atlassian.com/console/install/739e4d67-7f9e-409e-ad84-73ac9fbebc91?signature=5f2864f58d8c12b7754e0b767bd5c40c5425f55f0b8b72ac767d2928eb73c262a8004b312199ee15deb853265a1c0d34c405619e93cd171d9b5278c341c5a066&product=jira",
    repository:
      "https://github.com/0xAlphaDevs/Atlassian-Forge-Jira-Summarizer",
    body: { code: "" },
    path: "string",
    slug: "04",
  },
  {
    _id: "string",
    _raw: {},
    type: "Project",
    published: false,
    title: "P4W3-sbtify-contracts",
    description:
      "An app that condenses Jira issue descriptions and auto-generates PR summaries for streamlined project management.A trained model (llama-2-7b-chat) is used to summarize text in Jira Software issues. This Jira app intelligently summarizes text within Jira issues, providing clear overviews of complex and lengthy technical descriptions. The app uses Jira APIs, forge cli and forge api libraries to achieve this.",
    date: "2023-10-15T00:00:00.000Z",
    url: "",
    repository: "https://github.com/0xAlphaDevs/P4W3-sbtify-contracts",
    body: { code: "" },
    path: "string",
    slug: "05",
  },
];
